[build]
  command = "NODE_OPTIONS=--openssl-legacy-provider npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "camera=*"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"