[build]
  command = "yarn build"
  publish = "build"

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "camera=*"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"