[build]
  command = "npm ci --legacy-peer-deps && npm run build:netlify"
  publish = "build"

[build.environment]
  NODE_VERSION = "16"
  NPM_CONFIG_PREFER_OFFLINE = "true"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "camera=*"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"